name: Build
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      # Paso 2: Análisis de SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Paso 3: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Paso 4: Construir la imagen Docker
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/as221s6_t04_kr_wallet:latest .

      # Paso 5: Publicar la imagen Docker en Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/as221s6_t04_kr_wallet:latest
